# Generated by Django 5.1.1 on 2024-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_playlist',
        ),
        migrations.AddField(
            model_name='video',
            name='hls_playlists',
            field=models.JSONField(default=dict),
        ),
    ]
